#pragma kernel CSMain
#pragma target 4.5

Texture2D<float4> _TexA;     // input A
Texture2D<float4> _TexB;     // persistent input B
RWTexture2D<float4> _Result; // temporary output

int _Width;
int _Height;
float _DeltaTime;
float _SnowflakeHeight;
float _SnowflakeChance;
bool _Accumulate;


// https://discussions.unity.com/t/generate-random-float-between-0-and-1-in-shader/728060
float rand(float2 co)
{
    return frac(sin(dot(co, float2(12.9898, 78.233))) * 43758.5453);
}

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _Width || id.y >= _Height)
        return;

    int2 uv = int2(id.xy);
    float4 a = _TexA[uv];
    float4 b = _TexB[uv];

    _Result[uv] = saturate(a + b);

    float r = rand(id.xy * _DeltaTime);
    
    // combine with new depth map and add falling snow
    if (_Accumulate && r < _SnowflakeChance)
        _Result[uv] -= _SnowflakeHeight * _DeltaTime;
        // _Result[uv] = saturate(a + b - _SnowRate * _DeltaTime);
    else
        _Result[uv] = saturate(a + b);
}